### ISSUE TITLE
Add more artifacts to GitHub releases

### ISSUE THREAD

**Issue by natestemen** [unitaryfoundation/mitiq#1771]
Currently as part of our GitHub releases (e.g. [0.25.0](https://github.com/unitaryfund/mitiq/releases/tag/v0.25.0)) we only include source code. Dan mentioned that it could be nice to include wheels as part of this release, and I tend to agree.

The main benefit of this would be to allow users an additional install option.

---

This came out of walking through the Mitiq release pipeline with @Misty-W and @WrathfulSpatula during today's release.

**Comment by natestemen** [comment]
@ACE07-Sev to follow up if wheels are typically included in releases, or just on PyPI.

**Comment by ACE07-Sev** [comment]
@natestemen Nate I checked and asked the guys who work more with ci build tools, and this is the summary:

- Projects that are pure-python do not need wheels for different OS and architecture. A single one suffices.
- Multiple wheels like that is meant for projects that use compiled languages in their src, like qiskit (uses rust) or pyqrack (uses c++). We usually use `cibuildwheel` as a workflow to generate them, and those get pushed to just pypi (i.e., look at `Download Files` of pyqrack, you'll see the wheels there, same for qiskit), not releases on github (it's obsolete there as far as I can tell). It's useful for pypi because it doesn't have to build the compiled part as you install, which saves a lot of time (https://pradyunsg.me/blog/2022/12/31/wheels-are-faster-pure-python/#the-picture-answer).

From what I can see you use pure-python. So, this can be closed (you don't need it, nor have use for it). In any case if you do end up using other compiled languages at some point in the future, I made a workflow for you which I'll drop here for your kind reference.

```
name: Upload Release Package to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs: {}

jobs:
  build_wheels:
    if: github.repository_owner == 'unitaryfoundation'
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # To build wheels for more platforms, add them here.
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Check out mitiq
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v3.1.2

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
          path: ./wheelhouse/*.whl

  build_sdist:
    if: github.repository_owner == 'unitaryfoundation'
    name: Build source distribution
    runs-on: ubuntu-latest
    steps:
      - name: Check out mitiq
        uses: actions/checkout@v5
        with:
          ref: ${{ github.ref }}

      - name: Build sdist
        run: pipx run build --sdist

      - name: Upload sdist
        uses: actions/upload-artifact@v4
        with:
          name: cibw-sdist
          path: dist/*.tar.gz

  upload_pypi:
    if: github.repository_owner == 'unitaryfoundation'
    needs: [build_wheels, build_sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          # unpacks all CIBW artifacts into dist/
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@v1.12.4
        with:
          skip-existing: true
          verbose: true
          print-hash: true
```
